baseURL = 'https://maggodee.us/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"    
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"    
    weight = 3

  [[menu.main]]
    name = "Archives"
    url = "/archives"    
    weight = 4  

  
